// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkN0LLwKBt_LuPtoU-nBQU7xtSq7LqGn0',
    appId: '1:662322157210:web:173bf2e4fa03ae209a3123',
    messagingSenderId: '662322157210',
    projectId: 'mesafer-431a0',
    authDomain: 'mesafer-431a0.firebaseapp.com',
    storageBucket: 'mesafer-431a0.appspot.com',
    measurementId: 'G-16KRG55LQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7_0kqfEis0v5WWvtp-LyrxxTze9uRHxw',
    appId: '1:662322157210:android:ec280272277f3fe19a3123',
    messagingSenderId: '662322157210',
    projectId: 'mesafer-431a0',
    storageBucket: 'mesafer-431a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0xldt3I0n2G4oDgNJUpzn3Uwophd0ys',
    appId: '1:662322157210:ios:84bbfb8abfef38db9a3123',
    messagingSenderId: '662322157210',
    projectId: 'mesafer-431a0',
    storageBucket: 'mesafer-431a0.appspot.com',
    iosClientId: '662322157210-i0ll2pprsov75fhsa3mufkigrn22bm7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesafer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0xldt3I0n2G4oDgNJUpzn3Uwophd0ys',
    appId: '1:662322157210:ios:84bbfb8abfef38db9a3123',
    messagingSenderId: '662322157210',
    projectId: 'mesafer-431a0',
    storageBucket: 'mesafer-431a0.appspot.com',
    iosClientId: '662322157210-i0ll2pprsov75fhsa3mufkigrn22bm7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesafer',
  );
}
